/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Audio, Image, Pdf, Video } from "@boundaryml/baml"
import type * as types from "./types"
import type {
  Check,
  Checked,
  TextElement,
  ViewElement,
  Wireframe,
  Wireframes
} from "./types"

/******************************************************************************
 *
 *  These types are used for streaming, for when an instance of a type
 *  is still being built up and any of its fields is not yet fully available.
 *
 ******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
  export interface TextElement {
    tag?: "text" | null
    text?: string | null
    css?: string | null
  }
  export interface ViewElement {
    tag?: "view" | null
    children: (TextElement | ViewElement)[]
    css?: string | null
  }
  export interface Wireframe {
    elements: (TextElement | ViewElement)[]
  }
  export interface Wireframes {
    wireframes: types.Checked<Wireframe[], "more_than_3">
  }
  export type Element = TextElement | ViewElement | null
}
