import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { AutumnProvider } from "autumn-js/react"
import { ThemeProvider as NextThemesProvider } from "next-themes"
import { Toaster } from "../components/ui/sonner"
import publicConfig from "../lib/public-config"
import Tracker from "./tracker"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Ezzy Cloud",
  description: "Generated by create next app"
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextThemesProvider attribute="class" enableSystem>
          <AutumnProvider betterAuthUrl={publicConfig.BETTER_AUTH_URL}>
            {children}
          </AutumnProvider>
          <Toaster position="top-center" />
          <Tracker />
        </NextThemesProvider>
      </body>
    </html>
  )
}
